"""Embedded async client for the iQua cloud API (api.myiquaapp.com).

This package is the integration's self-contained iQua API layer: the auth token
lifecycle (:mod:`.auth`), the tolerant payload models (:mod:`.models`), the typed
error taxonomy (:mod:`.exceptions`), and the high-level device client
(:mod:`.client`). Everything downstream (config flow, coordinator, entities)
imports from here.
"""

from __future__ import annotations

from .auth import AuthManager, async_probe_host
from .client import AquaHomeClient
from .const import (
    API_BASE_URL,
    COMMAND_FUNCTIONS,
    FORBIDDEN_COMMAND_FUNCTIONS,
    IQUA2_BASE_URL,
    MAX_REFRESH_HOURS,
)
from .exceptions import (
    ApiError,
    AquaHomeConnectionError,
    AquaHomeError,
    AuthError,
    DeviceOfflineError,
    ForbiddenCommandError,
    RateLimitError,
    UserNotVerifiedError,
)
from .models import (
    SCALED_PROPERTIES,
    SENTINEL_DISABLED,
    UNVERIFIED_SCALED_PROPERTIES,
    Alert,
    AlertsPage,
    CommandResult,
    ConditionalRule,
    ConditionalRuleGroup,
    Conversion,
    ConvertedProperty,
    Datapoint,
    DatapointGraph,
    Device,
    DeviceSetting,
    DeviceSettingsDocument,
    DeviceSummary,
    FlowMonitorStatus,
    LeakDetector,
    LeakDetectorFlag,
    LeakDetectors,
    LeakDetectorStatus,
    LeakDetectorTemperature,
    LiveTicket,
    LoginResult,
    MultiSelectRules,
    NumberRules,
    PropertyValue,
    RateLimitStatus,
    RechargeAction,
    RechargeDialog,
    RechargeUi,
    RegenerationEvent,
    RegenerationEventsPage,
    RegenerationInfo,
    SaltLevel,
    SelectOption,
    SelectRules,
    SettingRules,
    TextRules,
    UserSummary,
    WaterShutoffValve,
    WaterTreatment,
    WaterTreatmentStatus,
    WsovDialog,
    WsovDialogButtons,
    scaled_value,
)

__all__ = [
    "API_BASE_URL",
    "COMMAND_FUNCTIONS",
    "FORBIDDEN_COMMAND_FUNCTIONS",
    "IQUA2_BASE_URL",
    "MAX_REFRESH_HOURS",
    "SCALED_PROPERTIES",
    "SENTINEL_DISABLED",
    "UNVERIFIED_SCALED_PROPERTIES",
    "Alert",
    "AlertsPage",
    "ApiError",
    "AquaHomeClient",
    "AquaHomeConnectionError",
    "AquaHomeError",
    "AuthError",
    "AuthManager",
    "CommandResult",
    "ConditionalRule",
    "ConditionalRuleGroup",
    "Conversion",
    "ConvertedProperty",
    "Datapoint",
    "DatapointGraph",
    "Device",
    "DeviceOfflineError",
    "DeviceSetting",
    "DeviceSettingsDocument",
    "DeviceSummary",
    "FlowMonitorStatus",
    "ForbiddenCommandError",
    "LeakDetector",
    "LeakDetectorFlag",
    "LeakDetectorStatus",
    "LeakDetectorTemperature",
    "LeakDetectors",
    "LiveTicket",
    "LoginResult",
    "MultiSelectRules",
    "NumberRules",
    "PropertyValue",
    "RateLimitError",
    "RateLimitStatus",
    "RechargeAction",
    "RechargeDialog",
    "RechargeUi",
    "RegenerationEvent",
    "RegenerationEventsPage",
    "RegenerationInfo",
    "SaltLevel",
    "SelectOption",
    "SelectRules",
    "SettingRules",
    "TextRules",
    "UserNotVerifiedError",
    "UserSummary",
    "WaterShutoffValve",
    "WaterTreatment",
    "WaterTreatmentStatus",
    "WsovDialog",
    "WsovDialogButtons",
    "async_probe_host",
    "scaled_value",
]
